using Poczatki;
using System.ComponentModel;

var employee = new Employee("Bartek", "Galant");
employee.AddGrade(2);
employee.AddGrade(20000);
employee.AddGrade("Bartek");
employee.AddGrade(8);
var stats1 = employee.GetStatisticsWithForEach();
Console.WriteLine("GetStatistics With ForEach");
Console.WriteLine($"Average: {stats1.Average:N2}");
Console.WriteLine("Min: " + stats1.Min);
Console.WriteLine($"Max: {stats1.Max}");
var stats2 = employee.GetStatisticsWithFor();
Console.WriteLine("GetStatistics With For");
Console.WriteLine($"Average: {stats2.Average:N2}");
Console.WriteLine("Min: " + stats2.Min);
Console.WriteLine($"Max: {stats2.Max}");
var stats3 = employee.GetStatisticsWithDoWhile();
Console.WriteLine("GetStatistics With DoWhile");
Console.WriteLine($"Average: {stats3.Average:N2}");
Console.WriteLine("Min: " + stats3.Min);
Console.WriteLine($"Max: {stats3.Max}");
var stats4 = employee.GetStatisticsWithWhile();
Console.WriteLine("GetStatistics With While");
Console.WriteLine($"Average: {stats4.Average:N2}");
Console.WriteLine("Min: " + stats4.Min);
Console.WriteLine($"Max: {stats4.Max}");